# Zigbee2MQTT Configuration
# Documentation: https://www.zigbee2mqtt.io/guide/configuration/

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  # user and password come from environment variables
  keepalive: 60
  reject_unauthorized: true
  version: 4

# Serial port settings
serial:
  port: ${ZIGBEE_SERIAL_PORT}
  adapter: zstack
  baudrate: 115200

# Web frontend
frontend:
  port: 8080

# Zigbee network settings
advanced:
  log_level: info
  log_output:
    - console
  network_key: [131, 239, 145, 218, 133, 95, 179, 251, 56, 133, 159, 145, 234, 208, 152, 208]
  pan_id: 56456
  ext_pan_id: [142, 154, 91, 219, 63, 24, 76, 220]
  channel: 25

# Device specific configuration
device_options:
  retain: true

# Permit devices to join
permit_join: false

# Home Assistant integration
homeassistant: true

# Device friendly names
devices:
  '0x00158d000ae4bfa1':
    friendly_name: Basement Zigbee Repeater
  '0x00158d008b152f40':
    friendly_name: Mudroom Interior Door
  '0x00158d008afd164e':
    friendly_name: Front Door
  '0x00158d008b152eac':
    friendly_name: Family Room Interior Door
  '0x00158d008b152ef4':
    friendly_name: Side Door
  '0x00158d008afd1723':
    friendly_name: Master Bedroom Door
  '0x00158d008afd161d':
    friendly_name: Attic Door
  '0x00158d000ae4be60':
    friendly_name: Kids Computer Plug
  '0x00158d000ae4be17':
    friendly_name: Erik's Lamp
  '0x00158d008b3349b5':
    friendly_name: Shed Door
  '0x00158d008b11b3c3':
    friendly_name: Mudroom Exterior Door
  '0x00158d008b3349ae':
    friendly_name: Family Room Patio Door
  '0x00158d008b3333a8':
    friendly_name: Family Room Back Door
  '0x00158d008b333401':
    friendly_name: Tilly's Bedroom Door
  '0x00158d008b301d1d':
    friendly_name: Hank's Bedroom Main Door
  '0x00158d008b301d8b':
    friendly_name: Hank's Bedroom Side Door
  '0x00158d008b155e10':
    friendly_name: Family Room Sliding Door 1
  '0x00158d008b153070':
    friendly_name: Family Room Sliding Door 2
  '0x00158d008b1167cf':
    friendly_name: Family Room Sliding Door 3
  '0x00158d008b155e00':
    friendly_name: Family Room Sliding Door 4
  '0x00158d000af012c7':
    friendly_name: Hot Water Heater Leak Sensor