version: '3.8'

services:
  mosquitto:
    # ... other config ...
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  zigbee2mqtt:
    # ... other config ...
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M