version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_RETENTION=1825d  # 5 years
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  telegraf:
    image: telegraf:1.31
    container_name: telegraf
    restart: unless-stopped
    network_mode: host
    hostname: docker-services-host
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/scripts:/etc/telegraf/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/hostfs/sys:ro
      - /proc:/hostfs/proc:ro
      - /etc:/hostfs/etc:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
    depends_on:
      influxdb:
        condition: service_healthy
    user: telegraf:999  # 999 is typically the docker group GID

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,yesoreyeram-boomtheme-panel
      - GF_SERVER_ROOT_URL=http://docker-services-host.lan:3000
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - monitoring
    depends_on:
      - influxdb

networks:
  monitoring:
    driver: bridge

volumes:
  influxdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/monitoring/influxdb  # Update this path to your dedicated storage
  influxdb_config:
    driver: local
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind  
      device: /mnt/monitoring/grafana  # Update this path to your dedicated storage