---
- name: Check if this is a Proxmox VE system
  stat:
    path: /etc/pve
  register: pve_check

- name: Fix Proxmox repositories
  when: pve_check.stat.exists
  block:
    - name: Remove Proxmox enterprise repository
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        line: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
        state: absent

    - name: Add Proxmox no-subscription repository
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        state: present
        filename: pve-no-subscription

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - sudo
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - git
      - htop
      - btop
      - vim
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user | default('root') }}"
    groups: docker
    append: yes
  when: ansible_user is defined and ansible_user != 'root'

- name: Install Docker SDK for Python
  apt:
    name: python3-docker
    state: present

- name: Create common directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/docker
    - /opt/docker/configs
    - /opt/docker/data
  become: yes