{
 "title": "Homelab Summary",
 "tags": [
  "summary",
  "overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Homelab UPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_ups_load\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"ups_name\"] == \"homelab\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value * 10.0}))"
    }
   ]
  },
  {
   "title": "Network UPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_ups_load\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"ups_name\"] == \"network\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value * 10.0}))"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_ups_load\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> last()\n  |> sum()\n  |> map(fn: (r) => ({r with _value: r._value * 10.0}))"
    }
   ]
  }
 ]
}