---
# Basic setup for Hatchery server
- name: Configure Hatchery server base system
  hosts: hatchery
  become: yes
  tasks:
    - name: Check if this is a Proxmox VE system
      stat:
        path: /etc/pve
      register: pve_check

    - name: Fix Proxmox repositories
      when: pve_check.stat.exists
      block:
        - name: Remove Proxmox enterprise repository file
          file:
            path: /etc/apt/sources.list.d/pve-enterprise.list
            state: absent

        - name: Remove Ceph enterprise repository file
          file:
            path: /etc/apt/sources.list.d/ceph.list
            state: absent

        - name: Add Proxmox no-subscription repository
          apt_repository:
            repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
            state: present
            filename: pve-no-subscription
            update_cache: no

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - sudo
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
          - git
          - htop
          - btop
          - vim
        state: present

    - name: Ensure .ssh directory exists
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Add SSH public key
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/erik.pub') }}"
        state: present