---
- name: Remove Proxmox subscription notice
  hosts: proxmox_hosts
  become: yes
  tasks:
    - name: Backup proxmoxlib.js
      copy:
        src: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        dest: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak
        remote_src: yes
        force: no

    - name: Remove subscription check
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: "data\\.status\\.toLowerCase\\(\\) !== 'active'"
        replace: "false"

    - name: Disable getSubscriptionStatus function
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: "getSubscriptionStatus: function\\(orig_callback\\)"
        replace: "getSubscriptionStatus: function(orig_callback) { return; }"

    - name: Comment out enterprise repository
      replace:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^(deb.*pve-enterprise)'
        replace: '#\1'
      when: ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Check if no-subscription repo exists
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        state: present
        create: no
      check_mode: yes
      register: repo_check
      failed_when: false

    - name: Add no-subscription repository
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        state: present
      when: repo_check.changed

    - name: Create re-apply script
      copy:
        dest: /usr/local/bin/remove-subscription-notice.sh
        mode: '0755'
        content: |
          #!/bin/bash
          # Re-apply subscription notice removal after Proxmox updates
          
          sed -i.bak "s/data\.status\.toLowerCase() !== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
          sed -i "s/getSubscriptionStatus: function(orig_callback)/getSubscriptionStatus: function(orig_callback) { return; }/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
          echo "Subscription notice removed. Clear browser cache to see changes."

    - name: Display completion message
      debug:
        msg: |
          Subscription notice removed successfully!
          
          IMPORTANT: Clear your browser cache or hard refresh (Ctrl+F5) to see the changes.
          
          To re-apply after Proxmox updates, run: /usr/local/bin/remove-subscription-notice.sh