---
- name: Setup Portainer Edge Agent on Remote Docker Hosts
  hosts: docker_hosts
  become: yes
  vars:
    portainer_url: "https://portainer.pequod.sh"
    edge_id: "{{ ansible_hostname }}-{{ ansible_default_ipv4.address | replace('.', '-') }}"
    
  tasks:
    - name: Get Portainer Edge key from Portainer UI
      debug:
        msg:
          - "Before running this playbook:"
          - "1. Go to {{ portainer_url }}"
          - "2. Navigate to Environments → Add environment"
          - "3. Select 'Docker Standalone' → 'Edge Agent'"
          - "4. Copy the Edge Key and update this playbook"
          - "5. Note the Edge ID if you want a specific one"
      tags: ['info']

    - name: Create Portainer Edge Agent directory
      file:
        path: /opt/docker/portainer-agent
        state: directory
        mode: '0755'

    - name: Create docker-compose for Edge Agent
      copy:
        dest: /opt/docker/portainer-agent/docker-compose.yml
        content: |
          version: '3.8'
          
          services:
            edge-agent:
              image: portainer/agent:latest
              container_name: portainer_edge_agent
              restart: unless-stopped
              environment:
                - EDGE=1
                - EDGE_ID={{ edge_id }}
                - EDGE_KEY={{ edge_key | default('YOUR_EDGE_KEY_HERE') }}
                - EDGE_INSECURE_POLL=1  # Only if using self-signed certs
                - PORTAINER_URL={{ portainer_url }}
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - /var/lib/docker/volumes:/var/lib/docker/volumes
                - /opt/docker/portainer-agent:/data
              networks:
                - agent_net
          
          networks:
            agent_net:
              driver: bridge

    - name: Start Edge Agent
      command: docker compose up -d
      args:
        chdir: /opt/docker/portainer-agent
      when: edge_key is defined and edge_key != 'YOUR_EDGE_KEY_HERE'

    - name: Check Edge Agent status
      command: docker ps --filter name=portainer_edge_agent
      register: agent_status
      when: edge_key is defined

    - name: Show status
      debug:
        var: agent_status.stdout_lines
      when: edge_key is defined