---
- name: Show Monitoring Stack Credentials
  hosts: docker-services-host
  become: yes
  
  tasks:
    - name: Get InfluxDB password
      shell: grep "INFLUXDB_ADMIN_PASSWORD" /opt/docker/monitoring-stack/.env | cut -d= -f2
      register: influx_pass
      no_log: true

    - name: Get Grafana password
      shell: grep "GRAFANA_ADMIN_PASSWORD" /opt/docker/monitoring-stack/.env | cut -d= -f2
      register: grafana_pass
      no_log: true

    - name: Get InfluxDB token
      shell: grep "INFLUXDB_ADMIN_TOKEN" /opt/docker/monitoring-stack/.env | cut -d= -f2
      register: influx_token
      no_log: true

    - name: Show how to add to secrets.yaml
      debug:
        msg:
          - "Add these to your ansible/secrets.yaml:"
          - ""
          - "# Monitoring Stack"
          - "monitoring_influxdb_password: \"{{ influx_pass.stdout }}\""
          - "monitoring_grafana_password: \"{{ grafana_pass.stdout }}\""
          - "monitoring_influxdb_token: \"{{ influx_token.stdout }}\""
          - ""
          - "Then re-run the deployment to use these saved credentials"