---
- name: Show Portainer Admin Password
  hosts: docker-services-host
  become: yes
  gather_facts: no
  
  tasks:
    - name: Check if password file exists
      stat:
        path: /opt/docker/portainer/.portainer_password
      register: password_file
    
    - name: Read password from file
      slurp:
        src: /opt/docker/portainer/.portainer_password
      register: password_content
      when: password_file.stat.exists
    
    - name: Display password
      debug:
        msg:
          - "Portainer Admin Password: {{ password_content.content | b64decode | trim }}"
          - "URL: https://{{ inventory_hostname }}:9443"
      when: password_file.stat.exists
    
    - name: Password not found
      debug:
        msg: "Portainer password file not found. Run the portainer.yml playbook first."
      when: not password_file.stat.exists