---
- name: Verify Monitoring Stack Credentials
  hosts: docker-services-host
  become: yes
  vars_files:
    - /Users/erikwestlund/code/homelab/ansible/secrets.yaml
  
  tasks:
    - name: Check .env file for usernames and passwords
      shell: |
        echo "=== Current Monitoring Stack Credentials ==="
        grep -E "ADMIN_USER|ADMIN_PASSWORD" /opt/docker/monitoring-stack/.env | sed 's/PASSWORD=.*/PASSWORD=<hidden>/'
      register: env_check

    - name: Show current configuration
      debug:
        var: env_check.stdout_lines

    - name: Test Grafana login with credentials from secrets.yaml
      uri:
        url: "http://localhost:3000/api/admin/settings"
        user: "{{ monitoring.grafana.username }}"
        password: "{{ monitoring.grafana.password }}"
        force_basic_auth: yes
        status_code: [200, 401]
      register: grafana_test

    - name: Show login test results
      debug:
        msg:
          - "Grafana login test: {{ 'SUCCESS' if grafana_test.status == 200 else 'FAILED' }}"
          - "Using username: {{ monitoring.grafana.username }}"
          - ""
          - "Your monitoring stack is configured with:"
          - "  InfluxDB: {{ monitoring.influxdb.username }} / <password from secrets.yaml>"
          - "  Grafana: {{ monitoring.grafana.username }} / <password from secrets.yaml>"